### ISSUE TITLE
Do not disable focus outlines

### ISSUE THREAD

**Issue by oliverjam** [AsmahanM/FAC-To-Do-Project#40]
https://github.com/AsmahanM/FAC-To-Do-Project/blob/37b73c1e1fe13e9f6bc636482e6e809649de12c6/style.css#L182-L184
https://github.com/AsmahanM/FAC-To-Do-Project/blob/37b73c1e1fe13e9f6bc636482e6e809649de12c6/style.css#L195

Please never ever turn off the default focus outlines unless you are immediately replacing them with something _at least_ as visible. Your inputs/buttons are currently unusable without a mouse—if I hit `tab` to move my focus to one I have to guess where I am because there's no visual indicator.

A good analogy: try adding `cursor: none` to the `body` and see how hard it is to navigate the page 🙃

**Comment by AsmahanM** [comment]
Oh dear- this wasn't supposed to stay in the code 😨  Thanks for pointing it out! It's been removed now
